development:
  host: 'http://localhost:9200'
  transport_options:
    request:
      timeout: 15

test:
  host: 'http://localhost:9200'
  transport_options:
    request:
      timeout: 15

production:
  url: <%= ENV['ELASTICSEARCH_URL'] %>
  transport_options:
    request:
      timeout: 15